### ISSUE TITLE
Argparse scipts

### ISSUE THREAD

**Issue by carlos-pereyra** [pointwise/GeomToMesh#2]
I am interested in modifying these example scripts to accept command line arguments. An example demonstration of this might look like so:

`% <path-to-pointwise_install>/pointwise -b <path-to-scripts>/GeomToMesh.glf geometry-file user-defaults.glf --radius <something> -d <something>`

Is there any way to add argument parsing to a glyph script? Thanks.

**Comment by pabakertx** [comment]
GeomToMesh already accepts the first two command-line arguments (geometry-file and optional user-defaults script file). Look around line 943 of GeomToMesh.glf. (All user-customizable parameters are in the user-defaults script.)

It's not clear exactly what new arguments you want to pass in, but as these scripts are freely available, you may update them as needed to suit your own needs.

Hope this helps

**Comment by carlos-pereyra** [comment]
Sorry I should have specified that I would like the option of flag options. 

for instance rather than simply feeding in commandline arguments in sequential order, it would be better if there were flags

`pointwise some.glf --gimme <option>`
